// AUTO-GENERATED by scripts/sync_attachments.py - do not edit by hand.
// Re-run `npm run sync:attachments` after adding/removing PNGs in
// public/photos/attachments/.

export const ATTACHMENT_PHOTOS: Record<string, string[]> = {
  'attach_chain_black': ['/photos/attachments/attach_chain_black.png'],
  'attach_chain_orange': ['/photos/attachments/attach_chain_orange.png'],
  'attach_chain_red': ['/photos/attachments/attach_chain_red.png'],
  'attach_clasp_heart_blue': ['/photos/attachments/attach_clasp_heart_blue.png'],
  'attach_clasp_heart_orange': ['/photos/attachments/attach_clasp_heart_orange.png'],
  'attach_clasp_round_green': ['/photos/attachments/attach_clasp_round_green.png'],
  'attach_clasp_round_yellow': ['/photos/attachments/attach_clasp_round_yellow.png'],
};
