// AUTO-GENERATED by scripts/sync_beads.py — do not edit by hand.
// Re-run `npm run sync:beads` after adding/removing PNGs.

export const BEAD_PHOTOS: Record<string, string[]> = {
  'bead_bow_blue': ['/photos/beads/bead_bow_blue.png'],
  'bead_bow_lightblue': ['/photos/beads/bead_bow_lightblue.png'],
  'bead_bow_pearl': ['/photos/beads/bead_bow_pearl.png'],
  'bead_bow_pearl_v2': ['/photos/beads/bead_bow_pearl_v2.png'],
  'bead_carnelian_6': ['/photos/beads/bead_carnelian_6.png'],
  'bead_celeste_8': ['/photos/beads/bead_celeste_8.png'],
  'bead_flower_daisy': ['/photos/beads/bead_flower_daisy.png'],
  'bead_heart_black': ['/photos/beads/bead_heart_black.png'],
  'bead_moonstone_cube': ['/photos/beads/bead_moonstone_cube.png'],
  'bead_moonstone_iris_6': ['/photos/beads/bead_moonstone_iris_6.png'],
  'bead_onyx_tube': ['/photos/beads/bead_onyx_tube.png'],
  'bead_pearl_8_baroque': ['/photos/beads/bead_pearl_8_baroque.png'],
  'bead_star_green': ['/photos/beads/bead_star_green.png'],
  'bead_star_orange': ['/photos/beads/bead_star_orange.png'],
  'bead_turquoise_6': ['/photos/beads/bead_turquoise_6.png'],
  'bead_turquoise_8': ['/photos/beads/bead_turquoise_8.png'],
};
