// AUTO-GENERATED by scripts/sync_charms.py - do not edit by hand.
// Re-run `npm run sync:charms` after adding/removing PNGs in
// public/photos/charms/ or public/photos/figurines/.

export const CHARM_PHOTOS: Record<string, string[]> = {
  'charm_figurine_signature': ['/photos/figurines/charm_figurine_signature.png'],
};
