"""Scan public/photos/{charms,figurines}/ and compute the per-charm
anneau (attachment ring) vertical position as a fraction of the canvas
height. Generates src/lib/mocks/charm-anneau-offsets.generated.ts.

Why this exists
---------------
BraceletPreview renders each charm as a square image hanging from the cord.
The cord is supposed to pass through the charm's anneau (the small ring
that holds it on the bracelet wire). For that to look right, the renderer
needs to know WHERE in each PNG the anneau is — because PNG croppings vary
charm-to-charm (some have the anneau at the very top edge, others have
20-30% of padding above it).

Previously the renderer assumed a fixed 10 % offset for all charms. That
worked for charms with the anneau at exactly 10 % from the top, but the
rest appeared to "float" below the cord (gap between cord and anneau).

This script removes the guesswork: for each PNG, find the topmost row
that contains any non-transparent pixel. Express that row as a fraction
of the canvas height — that's anneauTopPct. The renderer then uses it
to offset the image so the anneau aligns with the cord.

Threshold
---------
We treat alpha > 32 as "opaque enough" to count. This skips the
anti-aliased fringes that PNG detouring leaves around the silhouette
(they're effectively invisible but technically non-zero alpha).

Output
------
src/lib/mocks/charm-anneau-offsets.generated.ts :

    export const CHARM_ANNEAU_OFFSETS: Record<string, number> = {
        'charm_eiffel_french': 0.22,
        'charm_lettre_u': 0.18,
        ...
    };

Run
---
    npm run sync:anneau-offsets
    # or:
    python scripts/compute_anneau_offsets.py
"""

from pathlib import Path
from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
PHOTOS_BASE = ROOT / 'public' / 'photos'
FOLDERS = ['charms', 'figurines']
OUT_TS = ROOT / 'src' / 'lib' / 'mocks' / 'charm-anneau-offsets.generated.ts'

# Alpha threshold — pixels with alpha at or below this are treated as
# transparent (PNG anti-aliased fringes typically have alpha 1-32).
ALPHA_THRESHOLD = 32


def topmost_opaque_row(img: Image.Image) -> int | None:
    """Return the Y of the topmost row that contains any pixel with
    alpha > ALPHA_THRESHOLD. Returns None for fully transparent images."""
    if img.mode != 'RGBA':
        img = img.convert('RGBA')
    alpha = img.split()[3]
    width, height = alpha.size
    # PIL gives us per-row access via getpixel — slower than numpy but no
    # external dependency. For our PNG sizes (~512 px) this completes in
    # milliseconds per file.
    pixels = alpha.load()
    for y in range(height):
        for x in range(width):
            if pixels[x, y] > ALPHA_THRESHOLD:
                return y
    return None


def compute_offset_for_png(png_path: Path) -> float | None:
    """Open the PNG, find the topmost opaque row, return its fraction
    of the canvas height. Returns None if the image is fully transparent
    or cannot be opened."""
    try:
        with Image.open(png_path) as img:
            top_y = topmost_opaque_row(img)
            if top_y is None:
                return None
            _, height = img.size
            return round(top_y / height, 4)
    except Exception as exc:
        print(f"  ! could not process {png_path.name}: {exc}")
        return None


def main() -> None:
    print("Scanning charm + figurine PNGs for anneau positions ...")
    entries: dict[str, float] = {}
    total = 0
    skipped: list[str] = []

    for folder in FOLDERS:
        d = PHOTOS_BASE / folder
        if not d.is_dir():
            print(f"  skipped: {d} (folder missing)")
            continue
        for png in sorted(d.glob('*.png')):
            total += 1
            charm_id = png.stem
            pct = compute_offset_for_png(png)
            if pct is None:
                skipped.append(charm_id)
                continue
            entries[charm_id] = pct

    if not entries:
        print("No valid PNGs found. Aborting.")
        return

    # Sort by id for stable diffs.
    sorted_entries = dict(sorted(entries.items()))

    # Generate the TS file.
    lines = [
        "// AUTO-GENERATED by scripts/compute_anneau_offsets.py — do not edit by hand.",
        "// Run `npm run sync:anneau-offsets` to refresh after re-detouring a charm PNG.",
        "//",
        "// Each entry is the vertical position of the topmost opaque pixel in the",
        "// charm's PNG, expressed as a fraction of the canvas height. BraceletPreview",
        "// uses this value to offset the image so the cord passes through the",
        "// charm's anneau (attachment ring) regardless of how much padding the",
        "// PNG has above the anneau.",
        "",
        "export const CHARM_ANNEAU_OFFSETS: Record<string, number> = {",
    ]
    for charm_id, pct in sorted_entries.items():
        lines.append(f"  {charm_id!r}: {pct},")
    lines.append("};")
    lines.append("")

    OUT_TS.write_text("\n".join(lines), encoding='utf-8')

    print(f"Wrote {len(entries)} entries -> {OUT_TS}")
    print(f"  Scanned {total} PNGs, {len(skipped)} fully-transparent (skipped)")
    if skipped:
        for s in skipped:
            print(f"    skipped: {s}")

    # Distribution summary so the user can spot outliers.
    values = sorted(entries.values())
    print()
    print("Distribution of anneauTopPct values:")
    print(f"  min   = {values[0]:.3f}")
    print(f"  p25   = {values[len(values)//4]:.3f}")
    print(f"  med   = {values[len(values)//2]:.3f}")
    print(f"  p75   = {values[3*len(values)//4]:.3f}")
    print(f"  max   = {values[-1]:.3f}")


if __name__ == '__main__':
    main()
