"""Scan public/photos/{charms,figurines}/ and generate src/lib/mocks/charm-photos.generated.ts.

Same convention as sync_beads.py : the PNG filename must match an `id`
defined in src/lib/mocks/charms.ts. The folder where the PNG lives encodes
the semantic kind :
    - public/photos/charms/<id>.png      → kind: 'charm'      (Classique)
    - public/photos/figurines/<id>.png   → kind: 'figurine'   (Kawaii)

Both folders contribute to a single CHARM_PHOTOS manifest because runtime
lookup only needs the URL — the discriminator lives on the Charm record
itself (the `kind` field in src/lib/mocks/charms.ts).

If the same id has PNGs in both folders, the first one encountered wins
and the duplicate is reported as a warning.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PHOTOS_BASE = ROOT / 'public' / 'photos'
FOLDERS = [
    ('charms', '/photos/charms/'),
    ('figurines', '/photos/figurines/'),
]
CHARMS_TS = ROOT / 'src' / 'lib' / 'mocks' / 'charms.ts'
OUT_TS = ROOT / 'src' / 'lib' / 'mocks' / 'charm-photos.generated.ts'


def known_charm_ids() -> set[str]:
    text = CHARMS_TS.read_text(encoding='utf-8')
    return set(re.findall(r"id:\s*'(charm_[a-z0-9_]+)'", text))


def main() -> None:
    for folder, _ in FOLDERS:
        (PHOTOS_BASE / folder).mkdir(parents=True, exist_ok=True)

    known = known_charm_ids()
    matched: dict[str, tuple[str, str]] = {}  # id -> (folder, url)
    unknown: list[str] = []
    duplicates: list[str] = []

    for folder, url_prefix in FOLDERS:
        folder_path = PHOTOS_BASE / folder
        for png in sorted(folder_path.glob('*.png')):
            cid = png.stem
            url = f"{url_prefix}{png.name}"
            if cid not in known:
                unknown.append(f"{folder}/{png.name}")
                continue
            if cid in matched:
                duplicates.append(f"{folder}/{png.name} (already matched in {matched[cid][0]}/)")
                continue
            matched[cid] = (folder, url)

    out = ['// AUTO-GENERATED by scripts/sync_charms.py - do not edit by hand.\n']
    out.append('// Re-run `npm run sync:charms` after adding/removing PNGs in\n')
    out.append('// public/photos/charms/ or public/photos/figurines/.\n\n')
    out.append('export const CHARM_PHOTOS: Record<string, string[]> = {\n')
    for cid, (_, url) in sorted(matched.items()):
        out.append(f"  {cid!r}: [{url!r}],\n")
    out.append('};\n')
    OUT_TS.write_text(''.join(out), encoding='utf-8')

    print(f"OK  {len(matched)} charm/figurine(s) linked to photos:")
    for k in sorted(matched):
        folder, _ = matched[k]
        print(f"    [{folder:<10}] {k}")
    if unknown:
        print(f"\nWARN  {len(unknown)} PNG(s) without a matching id (skipped):")
        for n in unknown:
            print(f"    {n}")
    if duplicates:
        print(f"\nWARN  {len(duplicates)} duplicate PNG(s) ignored:")
        for n in duplicates:
            print(f"    {n}")
    print(f"\n--> wrote {OUT_TS.relative_to(ROOT)}")


if __name__ == '__main__':
    main()
