"""Scan public/photos/attachments/ and generate
src/lib/mocks/attachment-photos.generated.ts.

Same convention as sync_beads.py / sync_charms.py : the PNG filename
must match an `id` defined in src/lib/mocks/attachments.ts. Two id
prefixes are scanned :
    - `attach_chain_<color>`  → small ball-chain that links the
                                 figurine to the bracelet wire (Kawaii)
    - `attach_clasp_<shape>_<color>` → snap ring/heart that hooks the
                                        chain onto the bracelet (Kawaii)

Both kinds live in a single folder (public/photos/attachments/) and a
single manifest because the runtime only needs the URL — the kind /
shape / color are properties on the catalogue record itself.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PHOTOS_DIR = ROOT / 'public' / 'photos' / 'attachments'
ATTACH_TS = ROOT / 'src' / 'lib' / 'mocks' / 'attachments.ts'
OUT_TS = ROOT / 'src' / 'lib' / 'mocks' / 'attachment-photos.generated.ts'


def known_attachment_ids() -> set[str]:
    if not ATTACH_TS.exists():
        return set()
    text = ATTACH_TS.read_text(encoding='utf-8')
    # Matches both attach_chain_* and attach_clasp_*
    return set(re.findall(r"id:\s*'(attach_[a-z0-9_]+)'", text))


def main() -> None:
    PHOTOS_DIR.mkdir(parents=True, exist_ok=True)

    known = known_attachment_ids()
    matched: dict[str, str] = {}
    unknown: list[str] = []

    for png in sorted(PHOTOS_DIR.glob('*.png')):
        cid = png.stem
        url = f"/photos/attachments/{png.name}"
        if cid not in known:
            unknown.append(png.name)
            continue
        matched[cid] = url

    out = ['// AUTO-GENERATED by scripts/sync_attachments.py - do not edit by hand.\n']
    out.append('// Re-run `npm run sync:attachments` after adding/removing PNGs in\n')
    out.append('// public/photos/attachments/.\n\n')
    out.append('export const ATTACHMENT_PHOTOS: Record<string, string[]> = {\n')
    for cid in sorted(matched):
        out.append(f"  {cid!r}: [{matched[cid]!r}],\n")
    out.append('};\n')
    OUT_TS.write_text(''.join(out), encoding='utf-8')

    print(f"OK  {len(matched)} attachment(s) linked to photos:")
    for k in sorted(matched):
        print(f"    {k}")
    if unknown:
        print(f"\nWARN  {len(unknown)} PNG(s) without a matching id (skipped):")
        for n in unknown:
            print(f"    {n}")
    print(f"\n--> wrote {OUT_TS.relative_to(ROOT)}")


if __name__ == '__main__':
    main()
