"""Scan public/photos/beads/ and generate src/lib/mocks/bead-photos.generated.ts.

Usage:
    python scripts/sync_beads.py

Convention :
    File names must match a bead `id` from src/lib/mocks/beads.ts.
    Example : `bead_amethyst_6.png` will be linked to the bead with
    id `bead_amethyst_6`.

The generator writes a `BEAD_PHOTOS` map that beads.ts merges into
each bead's `images` field at runtime. Re-run this script every
time you add or change photos.
"""
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PHOTOS_DIR = ROOT / 'public' / 'photos' / 'beads'
BEADS_TS = ROOT / 'src' / 'lib' / 'mocks' / 'beads.ts'
OUT_TS = ROOT / 'src' / 'lib' / 'mocks' / 'bead-photos.generated.ts'


def known_bead_ids() -> set[str]:
    """Parse beads.ts to extract all `id: '...'` values."""
    text = BEADS_TS.read_text(encoding='utf-8')
    return set(re.findall(r"id:\s*'(bead_[a-z0-9_]+)'", text))


def main() -> None:
    PHOTOS_DIR.mkdir(parents=True, exist_ok=True)
    known = known_bead_ids()

    matched: dict[str, str] = {}
    unknown: list[str] = []
    for png in sorted(PHOTOS_DIR.glob('*.png')):
        bead_id = png.stem
        url = f'/photos/beads/{png.name}'
        if bead_id in known:
            matched[bead_id] = url
        else:
            unknown.append(png.name)

    # Generate TS file
    out = ['// AUTO-GENERATED by scripts/sync_beads.py — do not edit by hand.\n']
    out.append('// Re-run `npm run sync:beads` after adding/removing PNGs.\n\n')
    out.append('export const BEAD_PHOTOS: Record<string, string[]> = {\n')
    for bead_id, url in sorted(matched.items()):
        out.append(f"  {bead_id!r}: [{url!r}],\n")
    out.append('};\n')
    OUT_TS.write_text(''.join(out), encoding='utf-8')

    print(f"OK  {len(matched)} bead(s) linked to photos:")
    for k in sorted(matched):
        print(f"    {k}")
    if unknown:
        print(f"\nWARN  {len(unknown)} PNG(s) without a matching bead id (skipped):")
        for n in unknown:
            print(f"    {n}")
        print('\nTo include them, either:')
        print(' - Rename the PNG to match an existing id from beads.ts')
        print(' - Or add a new entry in beads.ts with that id, then re-run')
    print(f"\n--> wrote {OUT_TS.relative_to(ROOT)}")


if __name__ == '__main__':
    main()
